apiVersion: v1
kind: Secret
metadata:
  name: {{ include "wonder-mesh-net.fullname" . }}-db
  labels:
    {{- include "wonder-mesh-net.labels" . | nindent 4 }}
type: Opaque
data:
  {{- $dsn := "" }}
  {{- if .Values.postgres.enabled }}
  {{- $dsn = .Values.coordinator.database.dsn | default (printf "postgres://%s:%s@%s-postgresql:%d/%s?sslmode=disable" .Values.postgres.auth.username .Values.postgres.auth.password (include "wonder-mesh-net.fullname" .) (.Values.postgres.service.port | int) .Values.postgres.auth.database) }}
  {{- else }}
  {{- $dsn = .Values.coordinator.database.dsn }}
  {{- end }}
  db-dsn: {{ $dsn | b64enc | quote }}
