apiVersion: v1
kind: Secret
metadata:
  name: {{ include "wonder-mesh-net.fullname" . }}-db
  labels:
    {{- include "wonder-mesh-net.labels" . | nindent 4 }}
type: Opaque
data:
  db-dsn: {{ .Values.coordinator.database.dsn | b64enc | quote }}
