apiVersion: v1
kind: Service
metadata:
  name: {{ include "wonder-mesh-net.fullname" . }}
  labels:
    {{- include "wonder-mesh-net.labels" . | nindent 4 }}
spec:
  type: {{ .Values.service.type }}
  ports:
    - port: {{ .Values.service.port }}
      targetPort: 9080
      protocol: TCP
      name: http
  selector:
    {{- include "wonder-mesh-net.selectorLabels" . | nindent 4 }}
    app.kubernetes.io/component: coordinator
