{{- if .Values.keycloak.enabled -}}
apiVersion: v1
kind: Service
metadata:
  name: {{ include "wonder-mesh-net.fullname" . }}-keycloak
  labels:
    {{- include "wonder-mesh-net.labels" . | nindent 4 }}
spec:
  type: {{ .Values.keycloak.service.type }}
  ports:
    - port: {{ .Values.keycloak.service.port }}
      targetPort: 8080
      protocol: TCP
      name: http
  selector:
    {{- include "wonder-mesh-net.selectorLabels" . | nindent 4 }}
    app.kubernetes.io/component: keycloak
{{- end }}
