services:
  keycloak:
    image: quay.io/keycloak/keycloak:26.0
    container_name: keycloak
    command: start-dev --import-realm
    environment:
      KEYCLOAK_ADMIN: admin
      KEYCLOAK_ADMIN_PASSWORD: admin
      KC_HOSTNAME_URL: http://localhost:9090
      KC_HOSTNAME_ADMIN_URL: http://localhost:9090
      KC_HOSTNAME_STRICT: "false"
      KC_HTTP_RELATIVE_PATH: /
    volumes:
      - ./keycloak-realm.json:/opt/keycloak/data/import/realm.json
    ports:
      - "9090:8080"

  coordinator:
    build:
      context: ..
      dockerfile: e2e/Dockerfile
    container_name: coordinator
    network_mode: "host"
    environment:
      OIDC_ISSUER: http://localhost:9090/realms/wonder
      OIDC_CLIENT_ID: wonder
      OIDC_CLIENT_SECRET: wonder-secret
      OIDC_REDIRECT_URI: http://localhost:9080/auth/callback
    volumes:
      - coordinator-data:/data
    depends_on:
      - keycloak
    command:
      - "coordinator"
      - "--listen"
      - ":9080"
      - "--public-url"
      - "http://localhost:9080"

volumes:
  coordinator-data:
